databases:
  - name: task_manager_db
    databaseName: task_manager
    user: anastasia

services:
  - type: web
    name: task-manager
    runtime: python
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    buildCommand: "./entrypoint.sh"
    startCommand: "gunicorn task_manager.wsgi:application"
